import React from "react";
import { ResponsiveSwarmPlot } from "@nivo/swarmplot";

interface DataItem {
  id: string;
  price: number;
  volume: number;
  [key: string]: any;
}

const data: DataItem[] = [
  {
    id: "0.0",
    group: "Consumer Electronics",
    price: 340,
    volume: 11,
  },
  {
    id: "0.1",
    group: "Consumer Electronics",
    price: 230,
    volume: 13,
  },
  {
    id: "0.2",
    group: "Consumer Electronics",
    price: 51,
    volume: 15,
  },
  {
    id: "0.3",
    group: "Consumer Electronics",
    price: 240,
    volume: 20,
  },
  {
    id: "0.4",
    group: "Consumer Electronics",
    price: 125,
    volume: 10,
  },
  {
    id: "0.5",
    group: "Consumer Electronics",
    price: 43,
    volume: 4,
  },
  {
    id: "0.6",
    group: "Consumer Electronics",
    price: 460,
    volume: 7,
  },
  {
    id: "0.7",
    group: "Consumer Electronics",
    price: 382,
    volume: 19,
  },
  {
    id: "0.8",
    group: "Consumer Electronics",
    price: 213,
    volume: 9,
  },
  {
    id: "0.9",
    group: "Consumer Electronics",
    price: 22,
    volume: 11,
  },
  {
    id: "0.10",
    group: "Consumer Electronics",
    price: 234,
    volume: 4,
  },
  {
    id: "0.11",
    group: "Consumer Electronics",
    price: 192,
    volume: 12,
  },
  {
    id: "0.12",
    group: "Consumer Electronics",
    price: 437,
    volume: 7,
  },
  {
    id: "0.13",
    group: "Consumer Electronics",
    price: 22,
    volume: 7,
  },
  {
    id: "0.14",
    group: "Consumer Electronics",
    price: 334,
    volume: 4,
  },
  {
    id: "0.15",
    group: "Consumer Electronics",
    price: 60,
    volume: 13,
  },
  {
    id: "0.16",
    group: "Consumer Electronics",
    price: 212,
    volume: 18,
  },
  {
    id: "0.17",
    group: "Consumer Electronics",
    price: 373,
    volume: 13,
  },
  {
    id: "0.18",
    group: "Consumer Electronics",
    price: 372,
    volume: 14,
  },
  {
    id: "0.19",
    group: "Consumer Electronics",
    price: 372,
    volume: 17,
  },
  {
    id: "0.20",
    group: "Consumer Electronics",
    price: 326,
    volume: 4,
  },
  {
    id: "0.21",
    group: "Consumer Electronics",
    price: 113,
    volume: 7,
  },
  {
    id: "0.22",
    group: "Consumer Electronics",
    price: 454,
    volume: 5,
  },
  {
    id: "0.23",
    group: "Consumer Electronics",
    price: 144,
    volume: 18,
  },
  {
    id: "0.24",
    group: "Consumer Electronics",
    price: 495,
    volume: 12,
  },
  {
    id: "0.25",
    group: "Consumer Electronics",
    price: 222,
    volume: 7,
  },
  {
    id: "0.26",
    group: "Consumer Electronics",
    price: 185,
    volume: 11,
  },
  {
    id: "0.27",
    group: "Consumer Electronics",
    price: 490,
    volume: 8,
  },
  {
    id: "0.28",
    group: "Consumer Electronics",
    price: 131,
    volume: 4,
  },
  {
    id: "0.29",
    group: "Consumer Electronics",
    price: 467,
    volume: 8,
  },
  {
    id: "0.30",
    group: "Consumer Electronics",
    price: 243,
    volume: 10,
  },
  {
    id: "0.31",
    group: "Consumer Electronics",
    price: 430,
    volume: 19,
  },
  {
    id: "0.32",
    group: "Consumer Electronics",
    price: 229,
    volume: 7,
  },
  {
    id: "0.33",
    group: "Consumer Electronics",
    price: 148,
    volume: 7,
  },
  {
    id: "0.34",
    group: "Consumer Electronics",
    price: 446,
    volume: 18,
  },
  {
    id: "0.35",
    group: "Consumer Electronics",
    price: 494,
    volume: 17,
  },
  {
    id: "0.36",
    group: "Consumer Electronics",
    price: 140,
    volume: 17,
  },
  {
    id: "0.37",
    group: "Consumer Electronics",
    price: 493,
    volume: 19,
  },
  {
    id: "0.38",
    group: "Consumer Electronics",
    price: 388,
    volume: 19,
  },
  {
    id: "0.39",
    group: "Consumer Electronics",
    price: 390,
    volume: 10,
  },
  {
    id: "0.40",
    group: "Consumer Electronics",
    price: 398,
    volume: 10,
  },
  {
    id: "0.41",
    group: "Consumer Electronics",
    price: 230,
    volume: 16,
  },
  {
    id: "0.42",
    group: "Consumer Electronics",
    price: 230,
    volume: 7,
  },
  {
    id: "0.43",
    group: "Consumer Electronics",
    price: 347,
    volume: 20,
  },
  {
    id: "0.44",
    group: "Consumer Electronics",
    price: 56,
    volume: 12,
  },
  {
    id: "0.45",
    group: "Consumer Electronics",
    price: 382,
    volume: 15,
  },
  {
    id: "0.46",
    group: "Consumer Electronics",
    price: 307,
    volume: 8,
  },
  {
    id: "0.47",
    group: "Consumer Electronics",
    price: 400,
    volume: 6,
  },
  {
    id: "0.48",
    group: "Consumer Electronics",
    price: 374,
    volume: 15,
  },
  {
    id: "0.49",
    group: "Consumer Electronics",
    price: 96,
    volume: 4,
  },
  {
    id: "0.50",
    group: "Consumer Electronics",
    price: 109,
    volume: 16,
  },
  {
    id: "0.51",
    group: "Consumer Electronics",
    price: 19,
    volume: 6,
  },
  {
    id: "0.52",
    group: "Consumer Electronics",
    price: 298,
    volume: 6,
  },
  {
    id: "0.53",
    group: "Consumer Electronics",
    price: 488,
    volume: 12,
  },
  {
    id: "0.54",
    group: "Consumer Electronics",
    price: 312,
    volume: 18,
  },
  {
    id: "0.55",
    group: "Consumer Electronics",
    price: 398,
    volume: 7,
  },
  {
    id: "0.56",
    group: "Consumer Electronics",
    price: 77,
    volume: 12,
  },
  {
    id: "0.57",
    group: "Consumer Electronics",
    price: 350,
    volume: 17,
  },
  {
    id: "0.58",
    group: "Consumer Electronics",
    price: 446,
    volume: 4,
  },
  {
    id: "0.59",
    group: "Consumer Electronics",
    price: 194,
    volume: 8,
  },
  {
    id: "0.60",
    group: "Consumer Electronics",
    price: 196,
    volume: 10,
  },
  {
    id: "0.61",
    group: "Consumer Electronics",
    price: 342,
    volume: 17,
  },
  {
    id: "0.62",
    group: "Consumer Electronics",
    price: 139,
    volume: 12,
  },
  {
    id: "0.63",
    group: "Consumer Electronics",
    price: 7,
    volume: 11,
  },
  {
    id: "0.64",
    group: "Consumer Electronics",
    price: 5,
    volume: 14,
  },
  {
    id: "0.65",
    group: "Consumer Electronics",
    price: 143,
    volume: 5,
  },
  {
    id: "0.66",
    group: "Consumer Electronics",
    price: 202,
    volume: 12,
  },
  {
    id: "1.0",
    group: "Fashion or Apparel",
    price: 11,
    volume: 14,
  },
  {
    id: "1.1",
    group: "Fashion or Apparel",
    price: 350,
    volume: 11,
  },
  {
    id: "1.2",
    group: "Fashion or Apparel",
    price: 437,
    volume: 9,
  },
  {
    id: "1.3",
    group: "Fashion or Apparel",
    price: 321,
    volume: 11,
  },
  {
    id: "1.4",
    group: "Fashion or Apparel",
    price: 135,
    volume: 6,
  },
  {
    id: "1.5",
    group: "Fashion or Apparel",
    price: 193,
    volume: 9,
  },
  {
    id: "1.6",
    group: "Fashion or Apparel",
    price: 82,
    volume: 15,
  },
  {
    id: "1.7",
    group: "Fashion or Apparel",
    price: 220,
    volume: 19,
  },
  {
    id: "1.8",
    group: "Fashion or Apparel",
    price: 286,
    volume: 12,
  },
  {
    id: "1.9",
    group: "Fashion or Apparel",
    price: 160,
    volume: 12,
  },
  {
    id: "1.10",
    group: "Fashion or Apparel",
    price: 71,
    volume: 5,
  },
  {
    id: "1.11",
    group: "Fashion or Apparel",
    price: 51,
    volume: 6,
  },
  {
    id: "1.12",
    group: "Fashion or Apparel",
    price: 93,
    volume: 4,
  },
  {
    id: "1.13",
    group: "Fashion or Apparel",
    price: 388,
    volume: 14,
  },
  {
    id: "1.14",
    group: "Fashion or Apparel",
    price: 385,
    volume: 11,
  },
  {
    id: "1.15",
    group: "Fashion or Apparel",
    price: 105,
    volume: 4,
  },
  {
    id: "1.16",
    group: "Fashion or Apparel",
    price: 15,
    volume: 12,
  },
  {
    id: "1.17",
    group: "Fashion or Apparel",
    price: 58,
    volume: 20,
  },
  {
    id: "1.18",
    group: "Fashion or Apparel",
    price: 103,
    volume: 14,
  },
  {
    id: "1.19",
    group: "Fashion or Apparel",
    price: 311,
    volume: 6,
  },
  {
    id: "1.20",
    group: "Fashion or Apparel",
    price: 59,
    volume: 14,
  },
  {
    id: "1.21",
    group: "Fashion or Apparel",
    price: 481,
    volume: 20,
  },
  {
    id: "1.22",
    group: "Fashion or Apparel",
    price: 103,
    volume: 4,
  },
  {
    id: "1.23",
    group: "Fashion or Apparel",
    price: 123,
    volume: 11,
  },
  {
    id: "1.24",
    group: "Fashion or Apparel",
    price: 271,
    volume: 16,
  },
  {
    id: "1.25",
    group: "Fashion or Apparel",
    price: 441,
    volume: 12,
  },
  {
    id: "1.26",
    group: "Fashion or Apparel",
    price: 96,
    volume: 20,
  },
  {
    id: "1.27",
    group: "Fashion or Apparel",
    price: 269,
    volume: 17,
  },
  {
    id: "1.28",
    group: "Fashion or Apparel",
    price: 349,
    volume: 9,
  },
  {
    id: "1.29",
    group: "Fashion or Apparel",
    price: 3,
    volume: 4,
  },
  {
    id: "1.30",
    group: "Fashion or Apparel",
    price: 251,
    volume: 9,
  },
  {
    id: "1.31",
    group: "Fashion or Apparel",
    price: 413,
    volume: 9,
  },
  {
    id: "1.32",
    group: "Fashion or Apparel",
    price: 471,
    volume: 15,
  },
  {
    id: "1.33",
    group: "Fashion or Apparel",
    price: 217,
    volume: 8,
  },
  {
    id: "1.34",
    group: "Fashion or Apparel",
    price: 384,
    volume: 19,
  },
  {
    id: "1.35",
    group: "Fashion or Apparel",
    price: 189,
    volume: 9,
  },
  {
    id: "1.36",
    group: "Fashion or Apparel",
    price: 147,
    volume: 19,
  },
  {
    id: "1.37",
    group: "Fashion or Apparel",
    price: 302,
    volume: 8,
  },
  {
    id: "1.38",
    group: "Fashion or Apparel",
    price: 379,
    volume: 17,
  },
  {
    id: "1.39",
    group: "Fashion or Apparel",
    price: 68,
    volume: 13,
  },
  {
    id: "1.40",
    group: "Fashion or Apparel",
    price: 45,
    volume: 4,
  },
  {
    id: "1.41",
    group: "Fashion or Apparel",
    price: 100,
    volume: 13,
  },
  {
    id: "1.42",
    group: "Fashion or Apparel",
    price: 199,
    volume: 10,
  },
  {
    id: "1.43",
    group: "Fashion or Apparel",
    price: 66,
    volume: 20,
  },
  {
    id: "1.44",
    group: "Fashion or Apparel",
    price: 291,
    volume: 15,
  },
  {
    id: "1.45",
    group: "Fashion or Apparel",
    price: 56,
    volume: 9,
  },
  {
    id: "1.46",
    group: "Fashion or Apparel",
    price: 441,
    volume: 8,
  },
  {
    id: "1.47",
    group: "Fashion or Apparel",
    price: 159,
    volume: 18,
  },
  {
    id: "1.48",
    group: "Fashion or Apparel",
    price: 183,
    volume: 15,
  },
  {
    id: "1.49",
    group: "Fashion or Apparel",
    price: 233,
    volume: 19,
  },
  {
    id: "1.50",
    group: "Fashion or Apparel",
    price: 178,
    volume: 14,
  },
  {
    id: "1.51",
    group: "Fashion or Apparel",
    price: 125,
    volume: 6,
  },
  {
    id: "1.52",
    group: "Fashion or Apparel",
    price: 175,
    volume: 20,
  },
  {
    id: "1.53",
    group: "Fashion or Apparel",
    price: 62,
    volume: 15,
  },
  {
    id: "1.54",
    group: "Fashion or Apparel",
    price: 122,
    volume: 17,
  },
  {
    id: "1.55",
    group: "Fashion or Apparel",
    price: 273,
    volume: 11,
  },
  {
    id: "1.56",
    group: "Fashion or Apparel",
    price: 115,
    volume: 13,
  },
  {
    id: "1.57",
    group: "Fashion or Apparel",
    price: 177,
    volume: 19,
  },
  {
    id: "1.58",
    group: "Fashion or Apparel",
    price: 366,
    volume: 11,
  },
  {
    id: "1.59",
    group: "Fashion or Apparel",
    price: 88,
    volume: 11,
  },
  {
    id: "1.60",
    group: "Fashion or Apparel",
    price: 284,
    volume: 10,
  },
  {
    id: "1.61",
    group: "Fashion or Apparel",
    price: 181,
    volume: 17,
  },
  {
    id: "1.62",
    group: "Fashion or Apparel",
    price: 245,
    volume: 20,
  },
  {
    id: "1.63",
    group: "Fashion or Apparel",
    price: 147,
    volume: 11,
  },
  {
    id: "1.64",
    group: "Fashion or Apparel",
    price: 104,
    volume: 7,
  },
  {
    id: "1.65",
    group: "Fashion or Apparel",
    price: 182,
    volume: 19,
  },
  {
    id: "2.0",
    group: "Food & Beverages",
    price: 470,
    volume: 4,
  },
  {
    id: "2.1",
    group: "Food & Beverages",
    price: 367,
    volume: 7,
  },
  {
    id: "2.2",
    group: "Food & Beverages",
    price: 13,
    volume: 8,
  },
  {
    id: "2.3",
    group: "Food & Beverages",
    price: 69,
    volume: 6,
  },
  {
    id: "2.4",
    group: "Food & Beverages",
    price: 383,
    volume: 7,
  },
  {
    id: "2.5",
    group: "Food & Beverages",
    price: 43,
    volume: 16,
  },
  {
    id: "2.6",
    group: "Food & Beverages",
    price: 362,
    volume: 20,
  },
  {
    id: "2.7",
    group: "Food & Beverages",
    price: 32,
    volume: 4,
  },
  {
    id: "2.8",
    group: "Food & Beverages",
    price: 492,
    volume: 20,
  },
  {
    id: "2.9",
    group: "Food & Beverages",
    price: 448,
    volume: 17,
  },
  {
    id: "2.10",
    group: "Food & Beverages",
    price: 307,
    volume: 12,
  },
  {
    id: "2.11",
    group: "Food & Beverages",
    price: 312,
    volume: 17,
  },
  {
    id: "2.12",
    group: "Food & Beverages",
    price: 403,
    volume: 18,
  },
  {
    id: "2.13",
    group: "Food & Beverages",
    price: 2,
    volume: 16,
  },
  {
    id: "2.14",
    group: "Food & Beverages",
    price: 381,
    volume: 17,
  },
  {
    id: "2.15",
    group: "Food & Beverages",
    price: 485,
    volume: 10,
  },
  {
    id: "2.16",
    group: "Food & Beverages",
    price: 447,
    volume: 13,
  },
  {
    id: "2.17",
    group: "Food & Beverages",
    price: 295,
    volume: 6,
  },
  {
    id: "2.18",
    group: "Food & Beverages",
    price: 180,
    volume: 15,
  },
  {
    id: "2.19",
    group: "Food & Beverages",
    price: 201,
    volume: 4,
  },
  {
    id: "2.20",
    group: "Food & Beverages",
    price: 305,
    volume: 11,
  },
  {
    id: "2.21",
    group: "Food & Beverages",
    price: 406,
    volume: 19,
  },
  {
    id: "2.22",
    group: "Food & Beverages",
    price: 130,
    volume: 12,
  },
  {
    id: "2.23",
    group: "Food & Beverages",
    price: 22,
    volume: 17,
  },
  {
    id: "2.24",
    group: "Food & Beverages",
    price: 144,
    volume: 20,
  },
  {
    id: "2.25",
    group: "Food & Beverages",
    price: 4,
    volume: 11,
  },
  {
    id: "2.26",
    group: "Food & Beverages",
    price: 49,
    volume: 6,
  },
  {
    id: "2.27",
    group: "Food & Beverages",
    price: 494,
    volume: 12,
  },
  {
    id: "2.28",
    group: "Food & Beverages",
    price: 0,
    volume: 20,
  },
  {
    id: "2.29",
    group: "Food & Beverages",
    price: 115,
    volume: 19,
  },
  {
    id: "2.30",
    group: "Food & Beverages",
    price: 479,
    volume: 9,
  },
  {
    id: "2.31",
    group: "Food & Beverages",
    price: 192,
    volume: 7,
  },
  {
    id: "2.32",
    group: "Food & Beverages",
    price: 277,
    volume: 16,
  },
  {
    id: "2.33",
    group: "Food & Beverages",
    price: 126,
    volume: 9,
  },
  {
    id: "2.34",
    group: "Food & Beverages",
    price: 419,
    volume: 10,
  },
  {
    id: "2.35",
    group: "Food & Beverages",
    price: 317,
    volume: 16,
  },
  {
    id: "2.36",
    group: "Food & Beverages",
    price: 120,
    volume: 14,
  },
  {
    id: "2.37",
    group: "Food & Beverages",
    price: 57,
    volume: 19,
  },
  {
    id: "2.38",
    group: "Food & Beverages",
    price: 114,
    volume: 10,
  },
  {
    id: "2.39",
    group: "Food & Beverages",
    price: 475,
    volume: 4,
  },
  {
    id: "2.40",
    group: "Food & Beverages",
    price: 322,
    volume: 16,
  },
  {
    id: "2.41",
    group: "Food & Beverages",
    price: 91,
    volume: 6,
  },
  {
    id: "2.42",
    group: "Food & Beverages",
    price: 325,
    volume: 5,
  },
  {
    id: "2.43",
    group: "Food & Beverages",
    price: 379,
    volume: 17,
  },
  {
    id: "2.44",
    group: "Food & Beverages",
    price: 310,
    volume: 14,
  },
  {
    id: "2.45",
    group: "Food & Beverages",
    price: 186,
    volume: 14,
  },
  {
    id: "2.46",
    group: "Food & Beverages",
    price: 312,
    volume: 5,
  },
  {
    id: "2.47",
    group: "Food & Beverages",
    price: 93,
    volume: 11,
  },
  {
    id: "2.48",
    group: "Food & Beverages",
    price: 291,
    volume: 8,
  },
  {
    id: "2.49",
    group: "Food & Beverages",
    price: 434,
    volume: 19,
  },
  {
    id: "2.50",
    group: "Food & Beverages",
    price: 479,
    volume: 17,
  },
  {
    id: "2.51",
    group: "Food & Beverages",
    price: 293,
    volume: 12,
  },
  {
    id: "2.52",
    group: "Food & Beverages",
    price: 444,
    volume: 11,
  },
  {
    id: "2.53",
    group: "Food & Beverages",
    price: 311,
    volume: 20,
  },
  {
    id: "2.54",
    group: "Food & Beverages",
    price: 268,
    volume: 11,
  },
  {
    id: "2.55",
    group: "Food & Beverages",
    price: 405,
    volume: 19,
  },
  {
    id: "2.56",
    group: "Food & Beverages",
    price: 47,
    volume: 6,
  },
  {
    id: "2.57",
    group: "Food & Beverages",
    price: 343,
    volume: 9,
  },
  {
    id: "2.58",
    group: "Food & Beverages",
    price: 208,
    volume: 11,
  },
  {
    id: "2.59",
    group: "Food & Beverages",
    price: 172,
    volume: 9,
  },
  {
    id: "2.60",
    group: "Food & Beverages",
    price: 440,
    volume: 12,
  },
  {
    id: "2.61",
    group: "Food & Beverages",
    price: 38,
    volume: 14,
  },
  {
    id: "2.62",
    group: "Food & Beverages",
    price: 460,
    volume: 4,
  },
  {
    id: "2.63",
    group: "Food & Beverages",
    price: 85,
    volume: 8,
  },
  {
    id: "2.64",
    group: "Food & Beverages",
    price: 249,
    volume: 6,
  },
  {
    id: "2.65",
    group: "Food & Beverages",
    price: 256,
    volume: 20,
  },
  {
    id: "2.66",
    group: "Food & Beverages",
    price: 67,
    volume: 12,
  },
  {
    id: "2.67",
    group: "Food & Beverages",
    price: 152,
    volume: 13,
  },
  {
    id: "2.68",
    group: "Food & Beverages",
    price: 447,
    volume: 10,
  },
  {
    id: "2.69",
    group: "Food & Beverages",
    price: 359,
    volume: 7,
  },
];

const MyResponsiveSwarmPlot: React.FC = () => (
  <ResponsiveSwarmPlot
    data={data}
    groups={["Consumer Electronics", "Fashion or Apparel", "Food & Beverages"]}
    identity="id"
    value="price"
    valueFormat="$.2f"
    valueScale={{ type: "linear", min: 0, max: 500, reverse: false }}
    size={{
      key: "volume",
      values: [4, 20],
      sizes: [6, 20],
    }}
    forceStrength={4}
    simulationIterations={100}
    borderColor={{
      from: "color",
      modifiers: [
        ["darker", 0.6],
        ["opacity", 0.5],
      ],
    }}
    margin={{ top: 80, right: 100, bottom: 80, left: 100 }}
    axisTop={{
      orient: "top",
      tickSize: 10,
      tickPadding: 5,
      tickRotation: 0,
      legend: "group if vertical, price if horizontal",
      legendPosition: "middle",
      legendOffset: -46,
      truncateTickAt: 0,
    }}
    axisRight={{
      orient: "right",
      tickSize: 10,
      tickPadding: 5,
      tickRotation: 0,
      legend: "price if vertical, group if horizontal",
      legendPosition: "middle",
      legendOffset: 76,
      truncateTickAt: 0,
    }}
    axisBottom={{
      orient: "bottom",
      tickSize: 10,
      tickPadding: 5,
      tickRotation: 0,
      legend: "group if vertical, price if horizontal",
      legendPosition: "middle",
      legendOffset: 46,
      truncateTickAt: 0,
    }}
    axisLeft={{
      orient: "left",
      tickSize: 10,
      tickPadding: 5,
      tickRotation: 0,
      legend: "price if vertical, group if horizontal",
      legendPosition: "middle",
      legendOffset: -76,
      truncateTickAt: 0,
    }}
  />
);

export default MyResponsiveSwarmPlot;
